server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/foodmap
    username: appuser
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always # 항상 data.sql 스크립트를 실행하도록 설정

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true